source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'PodsIssue' do
    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'
    pod 'FBSDKShareKit'
    pod 'Google/CloudMessaging'
    pod 'Google/SignIn'
    pod 'Cloudinary'
    pod 'Alamofire'
    pod 'SwiftyJSON'
    pod 'RSKImageCropper'
    pod 'Color-Picker-for-iOS'
    pod 'DGElasticPullToRefresh'
    
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'Instabug'

    project '../PodsIssue.xcodeproj'
    
    target 'PodsIssueTests' do
        inherit! :search_paths
    end
end

# This is needed because Google libraries don't have BitCode enabled yet.
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end